# Welcome and preface {.unnumbered}

Thanks for your interest in this short course on Computational Social Science
for Sustainability. 

Briefly about me, the instructor, my name is Matt Turner. 
I am a lecturer in the Stanford Doerr School of Sustainability in
the department of Environmental Social Sciences. So far I have developed two
courses for the department: *Computational Social Science for Sustainability*
and *Agent-based Modeling*. This short course for IC2S2 is a combination of
material from the two, plus a preview of an additional course I am developing
for the coming academic year, *Opinion Change Modeling and Measurement*.

Below I summarize what I contribute here, including my motivations for and lessons learned
by focusing on the problem of our epoch, sustainability. This approach develops
theoretical models of behavior and opinion change. Idealized mechanistic models
can help us understand how various, simultaneous, and dynamic constraints
such as population size, social network, and social learning strategy affect
the diffusion of adaptive sustainable beahviors. 

The question of our age is whether people can join forces to collectively
and meaningfully push history out of its current rut of rapid ecological
collapse towards a sustainable future. Technological solutions to the climate and general ecological crisis are 
proliferating. But will enough people do them to matter? How can we design
social inteventions with confidence to promote sustainable practices to replace 
maladaptive behaviors that exhaust local resources? 

The model framework I develop here can help, or so I believe and hope you agree. 
The following chapters explain the theoretical and modeling framework for
modeling social behavior with applications to behavior diffusion, 
cooperation for natural resource conservation, norm inversion, and opinion
change. I will frame social science theory and computational model development
in terms of various problems in sustainability to demonstrate intended use and
to introduce sustainability to newcomers. We will see together
through programming examples how to rigorously test 
different intervention strategies. We will effectively prototype these
interventions as software simulations in a sort of "wind tunnel" like used to
design cars to instead choose between
different designs for convincing an initial group of people to, first, adopt a
sustainable practice. The second, but equally important, goal of sustainability
interventions is to induce a self-sustaining process of behavior diffusion,
where one by one people learn a sustainable practice through social interaction
over time. 

Sincere thanks again for your time and attention. [Feedback via
email](mailto:maturner@stanford.edu) is appreciated.

This website and associated course content is and will always be free, licensed under the [CC BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/) License.

## Preface

- The structure of this framework emerged as I developed my course
  *Computational Social Science for Sustainability*, with the selection pressure
  of being digestible and useful for students in the sustainability school. 
  In the course we present models of social behavior diffusion to understand how
  sustainable practices spread in different idealized social contexts. 
- This IC2S2 tutorial introduces a framework for models of social behavior to
  organize them based on their assumptions, structure, applications, and other
  details. This is meant to complement data-driven approaches such as data
  analysis to incentivize and optimize real-world sustainable behaviors such as
  coordinated charging.
- Developing theories of why some sustainable practices spread but others don't
  is essential to promote sustainable adaptation to climate change and other
  pressing sustainability problems. These are thoroughly encapsulated in the
  United Nation's Sustainable Development Goals (aka SDGs), a set of seventeen
  pillars of sustainability cutting across developing strong Institutions that
  protect Basic rights including sustainable access to resources. This requires
  Environmental and Ecological protection, especially climate action.
  Theoretical modeling is a powerful way to predict how common contextual
  differences, such as the heterogeneity of social contacts in a population, 
  will affect outcomes, so a general strategy can be chosen for an application
  of interest. In modern best-practices for social science, 
  any collection of data-driven approaches are most useful when they utilize 
  at least a common vocabulary or framework [@Deffner2024]. 
- A new observation language to accommodate alternative mechanistic formulations
  of the process of social diffusion. I designed this framework and 
  software as a step forward that simultaneously introduces newcomers 
  to the field who could put the theoretical
  core of social science to use. It seemed no single resource existed to
  do this in a highly-transferable programming language like R. R, furthermore,
  has a wide, active, disciplined, diverse, and vibrant set of scientific developers
  who could collectively be called the *tidyverse*, led by Hadley Wickham and
  the Posit Developers who create the RStudio IDE.
- So, in summary, these notes are a humble suggestion for a social behavior
  modeling framework for studying behavior diffusion, cooperation, norm
  inversion, and opinion change, just as the first four I have explored myself.
  This framework is meant to be generative, enabling users to explore the
  consequences of using one modeling assumption or another, such as comparing
  contagion-style learning with success-biased social learning. In Chapter 2 on
  Diffusion, I explain that  
  cultural evolution only occurs when learning is adaptive, for example if 
  behavior choices are made based on how successful the people are who do them.
  This is known as *success-biased learning* in the cultural evolution
  literature. Still, sometimes people choose things more or less randomly, so a
  *contagion*-based approach is better, where behaviors are learned completely
  stochastically.
