# Introduction

Indigenous peoples of the South Pacific Islands have managed coastal mangrove forest management to dissipate storm surges and prevent erosion, adaptations that have mitigated potential costs of climate change since long before human activity-driven (i.e., *anthropogenic*) climate change [@Nalau2018; @Pearson2020; @McNamara2020]. First peoples of western North America have similarly practiced prescribed burns to prevent destructive wildfires during times of drought since long before anthropogenic climate change [@Eisenberg2019; @Kolden2019]. Despite the wide availability of ancient climate change adaptation knowledge and myriad modern innovations, maladaptive responses to climate change often take their place. In the South Pacific, for example, some international aid groups promote sea wall construction instead of mangrove forests, but these are expensive to maintain and can even act like dams, keeping water in once it inevitably breaches [@Piggott-McKellar2020]. Forest management that limits thinning misses an opportunity to prevent destructive wildfires, while clear-cutting can increase atmospheric carbon dioxide and increase the risk of mudslides, possibly due to the polarized nature of interests and opinions in public forest governance [@Swette2023].

The varied success of different sustainable practices to diffuse or not begs several questions, which we will address in this course. Analyzing these will help us harness the positive factors promoting the spread of sustainable behaviors and so we can avoid the pitfalls that impede adaptation. First, what factors helped sustainable adaptations spread in successful cases? Second, what factors hinder success, leading to maladaptation? Finally, what patterns emerge when we collect and consolidate different studies analyzing these questions? While there are many different cognitive, social, and environmental factors involved in any given sustainability outcome, we focus here on an emerging consensus about a set of cognitive and social factors known to affect behavior choice in general, and sustainable practices more specifically.

### Agent-based models of sustainable interventions {.unnumbered}

We will analyze and draw on several real-world empirical studies of interventions to develop our agent-based models that we in turn will use to simulate interventions in order to *deduce* which strategies are most effective for *social interventions* to promote sustainability, and why. A *social intervention* (or just *intervention*) for promoting sustainability is any concerted effort where those promoting a sustainable practice introduces information about how to perform that practice to a population. *Deductive* methods complement \_i strategies are most effective and why in idealized, cost-free settings (cost-free at least compared to the cost of real-world social interventions at scale). Our empirically-motivated models The cognitive and social factors we identify are suitable for inclusion in *agent-based models* of social behavior that we use to deduce the emergent social outcomes we can expect from different strategies for social interventions to promote sustainable practices.

Low-cost experimentation with simulated sustainability social interventions are critical because unless progress is accelerated towards we can expect to "have 575 million people living in extreme poverty, 600 million people facing hunger, and 84 million children and young people out of school. Humanity will overshoot the Paris climate agreement's 1.5°C 'safe' guardrail on...temperature rise. And, at the current rate, it will take 300 years to attain gender equality" [@Malekpour2023, p. 250]. Accelerated transformations are required to reach goals necessary to avoid increasingly frequent and costly climate change disasters [@UnitedNations2023].

The [UN Sustainable Development Goals](https://sdgs.un.org/) help us focus and organize our work by providing concrete goals for evaluating progress towards sustainable development for all [@fig-sdg-vibe]. These goals include targets for institutional development that promotes basic conditions for human thriving (justice, equality, education, public health, and no poverty) so as to assemble and enable a critical mass of people to participate bringing about sustainable development. People cannot participate in sustainability if they suffer in poverty, from illness, or subjugation by authoritarians–all but the most zealous environmental defenders will fight on when these basic needs are unmet. Since progress has been slower than necessary.

Sustainability, then, has several different dimensions, all of which contribute to climate action and environmental protection. I have organized these goals into a coding system called the vIBE system, which stands for *vibrant Institutions* support *Basic* human needs of people who protect the *Environment*. All 17 goals and the organization system are illustrated in [@fig-sdg-vibe]. Organizing and connecting our work to has two benefits. First, it helps us identify which cognitive and social factors are at work in different sustainability foci. Second, it expands the corpus of existing research on which we draw to consolidate our social and cognitive theories of behavior change that we will apply to sustainability interventions.

![The 17 United Nations Sustainable Development Goals (SDGs) can be organized into groups for vibrant Institutions (Group I) that provide Basic needs (Group B) required for people to actively work towards Environmental and Ecological protection (Group E)–we dub this the vIBE coding of the sustainable development goals.](images/clipboard-3767214830.png){fig-align="center" width="400"}

In the rest of this introductory chapter we expand on the real-world examples given above of sustainable adaptations by formally identifying, categorizing, and representing different social and cognitive processes at work when people learn from, observe, and teach one another, and integrate that with their own personal experience. The urgent need to understand how sustainable behaviors spread in order to develop effective interventions forces us social scientists to radically rethink how we conceptualize social change to make it rigorous, reliable, and digestible by non-social scientists.

## Cognitive and social factors in agent-based models of sustainable adaptation

Exceptional cognitive capacities, along with fine-motor-control fingers and adaptations for long-distance running, enabled the unprecedented explosion of the human population in its \~2 million years of existence. All the fancy things we have done and made with these skills now threatens our very existence since over our existence we have developed technologies that could kill us all. At this current inflection point we face large-scale suffering or even extinction if inaction reigns. Therefore we must harness and advance our collective knowledge of collective intelligence [@Centola2022] and adaptation [@GalesicEtAl2023] with a theoretical and computational framework capable of integrating diverse, non-linear processes of social interaction. We call our theoretical framework *Computational Social Science for Sustainability*. In this course we introduce students to *Agent-based Models* of social behavior in the context of sustainability.

### Cognitive factors

-   The most basic cognitive capacity that we use for building our models of social behavior is the ability to learn from others. Humans have evolved the capacity to intergrate diverse individual experience and socially-acquired information [@Turner2023a]. Humans adaptively weight personal experience against socially-learned information depending on the amount of uncertainty present in one's environment [@Toyokawa2019; @Witt2024].
-   Returning to the South Pacific Island example above, the observation that Indigenous solutions may outperform maladaptive imported solutions is possibly a manifestation of a more general phenomenon that *locally-led* interventions that include the very stakeholders who must participate in the adaptation effort tend to be more successful [@McNamara2020]. There may be many factors contributing to this, including the fact that locally-led interventions may tend to be more appropriate for the locale of interest. Cognitively, though, the fact may be
