# Social science for sustainability modeling

With whom we interact and how we learn are essential components in explaining the puzzles of diffusion and belief change that underlie the transition to more sustainable practices. In this section we will introduce models of social behavior across different agent-based model configurations. The first chapter in this section covers Diffusion of Adaptations. Next, we show how models of Cooperation can help us understand and predict outcomes in environmental management problems that require stakeholders to do the same behavior, using cooperation with groundwater usage limit laws within a water district as a prototypical example. Next we will present a related behavioral puzzle, that of why certain social norms like gender norms generate inequity and inequality, and point to how modeling social behavior can help us identify potential strategies for reaching more equitable equilibriums. After this we switch out our cognitive model focused on learning and action to one of social influence, with which we analyze the basic factors underlying increasing extremism and polarization, which can affect adaptation outcomes. The last two chapters in this part of the book introduce advanced topics in modeling social systems: incorporating Uncertainty into social ABMs and how we can use reinforcement learning as a cognitive model for agents that will enable them to more flexibly integrate socially- and individually-obtained information more like real-world humans.